// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { FilesPane } from './FilesPane'
import { toggleFilesTree, GLOBAL_SHORTCUTS } from '../keymap'
const mocks = vi.hoisted(() => ({ readDir: vi.fn(), pin: vi.fn(), activePath: '/ws/src/main.ts', tabs: [{ path: '/ws/src/main.ts', preview: false, missing: false }] }))
vi.mock('../houston/bridge', () => ({ readDir: mocks.readDir }))
vi.mock('./EditorSurface', () => ({ EditorSurfaceBody: () => <div data-testid="test-editor" /> }))
vi.mock('./files/useFileTabs', () => ({ useFileTabs: () => ({ activePath: mocks.activePath, tabs: mocks.tabs, pinFile: mocks.pin, previewFile: vi.fn(), surface: { markdownReady: false, setError: vi.fn() }, dirty: false, markMissing: vi.fn(), labelFor: (path: string) => path.split('/').at(-1) }) }))
let observers: { callback: ResizeObserverCallback; target: Element }[]
const entry = (path: string, dir = false) => ({ name: path.split('/').at(-1), path, dir, ignored: false })
const mount = () => render(<div className="side-card"><FilesPane panel node={{ kind: 'files', id: 'files', root: '/ws' }} workspaceDir="/ws" onClose={vi.fn()} onHeaderPointerDown={vi.fn()} /></div>)
function resize(width: number) {
  act(() => { for (const observer of observers) if (observer.target.matches('[data-testid="files-pane"]')) observer.callback([{ contentRect: { width } } as ResizeObserverEntry], {} as ResizeObserver) })
}
beforeEach(() => {
  localStorage.clear(); observers = []; vi.clearAllMocks()
  vi.stubGlobal('ResizeObserver', class { callback: ResizeObserverCallback; constructor(callback: ResizeObserverCallback) { this.callback = callback } observe(target: Element) { observers.push({ callback: this.callback, target }) } disconnect() {} })
  mocks.readDir.mockImplementation(async (path: string) => path === '/ws' ? [entry('/ws/src', true), entry('/ws/other.ts')] : [entry('/ws/src/main.ts'), entry('/ws/src/unused.ts')])
})
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
describe('Files panel split', () => {
  it('switches at the Files container threshold and hides tabs in stacked mode', async () => {
    mount(); resize(719)
    expect(screen.getByTestId('files-pane').dataset.split).toBe('false')
    expect(screen.queryByRole('tablist')).toBeNull()
    resize(720)
    expect(screen.getByTestId('files-pane').dataset.split).toBe('true')
    expect(screen.getByRole('tablist')).toBeTruthy()
    expect(screen.getByRole('textbox', { name: 'Filter files' })).toBeTruthy()
    resize(600)
    expect(screen.queryByRole('tablist')).toBeNull()
    expect(await screen.findByTestId('test-editor')).toBeTruthy()
  })
  it('clamps, persists, restores and resets the sash width', () => {
    const view = mount(); resize(760)
    const sash = screen.getByRole('separator', { name: 'Resize file tree' })
    expect(sash.getAttribute('aria-valuenow')).toBe('232')
    for (let i = 0; i < 30; i++) fireEvent.keyDown(sash, { key: 'ArrowRight' })
    expect(sash.getAttribute('aria-valuenow')).toBe('360')
    expect(JSON.parse(localStorage.getItem('tr-files-split:/ws')!).width).toBe(360)
    for (let i = 0; i < 30; i++) fireEvent.keyDown(sash, { key: 'ArrowLeft' })
    expect(sash.getAttribute('aria-valuenow')).toBe('200')
    view.unmount(); mount(); resize(1040)
    expect(screen.getByRole('separator').getAttribute('aria-valuenow')).toBe('200')
    fireEvent.doubleClick(screen.getByRole('separator'))
    expect(screen.getByRole('separator').getAttribute('aria-valuenow')).toBe('288')
  })
  it('resizes by pointer drag and stops resizing when capture ends', () => {
    vi.stubGlobal('PointerEvent', MouseEvent)
    mount(); resize(1040)
    const sash = screen.getByRole('separator') as HTMLElement & { setPointerCapture: (id: number) => void }
    sash.setPointerCapture = vi.fn()
    fireEvent.pointerDown(sash, { button: 0, clientX: 300 })
    fireEvent.pointerMove(sash, { clientX: 1000 })
    expect(sash.getAttribute('aria-valuenow')).toBe('360')
    expect(sash.dataset.dragging).toBe('true')
    fireEvent.pointerMove(sash, { clientX: 0 })
    expect(sash.getAttribute('aria-valuenow')).toBe('200')
    fireEvent.pointerUp(sash)
    fireEvent.pointerMove(sash, { clientX: 600 })
    expect(sash.getAttribute('aria-valuenow')).toBe('200')
    expect(sash.dataset.dragging).toBe('false')
  })
  it('persists collapse and toggles it with the free scoped chord', () => {
    const view = mount(); resize(1040)
    fireEvent.click(screen.getByRole('button', { name: 'Collapse tree' }))
    expect(screen.getByTestId('files-tree-column').style.display).toBe('none')
    expect(JSON.parse(localStorage.getItem('tr-files-split:/ws')!).collapsed).toBe(true)
    view.unmount(); mount(); resize(1040)
    expect(screen.getByRole('button', { name: 'Show tree' })).toBeTruthy()
    fireEvent.keyDown(screen.getByRole('button', { name: 'Show tree' }), { key: 't', code: 'KeyT', ctrlKey: true, altKey: true })
    expect(screen.getByTestId('files-tree-column').style.display).toBe('flex')
    const event = new KeyboardEvent('keydown', { key: 't', code: 'KeyT', ctrlKey: true, altKey: true })
    expect(GLOBAL_SHORTCUTS.filter((entry) => !entry.layer && entry.match?.(event))).toEqual([])
    expect(toggleFilesTree.keyLabel).toBe('Ctrl+Alt+T')
  })
  it('filters case-insensitively, keeps ancestors and clears on Escape', async () => {
    mount(); resize(1040)
    await waitFor(() => expect(screen.getAllByRole('treeitem')).toHaveLength(4))
    const filter = screen.getByRole('textbox', { name: 'Filter files' })
    fireEvent.change(filter, { target: { value: 'MAIN' } })
    expect(screen.getAllByRole('treeitem').map((row) => row.getAttribute('data-path'))).toEqual(['/ws/src', '/ws/src/main.ts'])
    fireEvent.keyDown(filter, { key: 'Escape' })
    expect(screen.getAllByRole('treeitem')).toHaveLength(4)
  })
  it('a breadcrumb reveals, expands and focuses the folder after collapse', async () => {
    mount(); resize(1040)
    await waitFor(() => expect(screen.getAllByRole('treeitem')).toHaveLength(4))
    fireEvent.click(screen.getByRole('button', { name: 'Collapse all' }))
    fireEvent.click(screen.getByRole('button', { name: 'Collapse tree' }))
    fireEvent.click(screen.getByRole('navigation', { name: 'File breadcrumb' }).querySelector('button')!)
    await waitFor(() => expect(screen.getAllByRole('treeitem')).toHaveLength(4))
    expect(screen.getByTestId('files-tree-column').style.display).toBe('flex')
    expect(document.activeElement?.getAttribute('data-path')).toBe('/ws/src')
  })
  it('pins terminal links through the existing openFile prop', () => {
    render(<FilesPane panel openFile={{ path: '/ws/src/main.ts', line: 2, col: 4 }} node={{ kind: 'files', id: 'files' }} workspaceDir="/ws" onClose={vi.fn()} onHeaderPointerDown={vi.fn()} />)
    expect(mocks.pin).toHaveBeenCalledWith('/ws/src/main.ts')
  })
})
