import type { ReactNode } from 'react'
import { Text } from './Text'

export function Prose({ children, variant, ...props }: { children: ReactNode; variant: 'editor' | 'chat'; className?: string; 'data-testid'?: string }): React.JSX.Element {
  const editor = variant === 'editor'
  const classes = editor
    ? '[&_h1]:[font-size:var(--tr-text-heading-size)] [&_h2]:[font-size:var(--tr-text-subhead-size)] [&_h3]:[font-size:var(--tr-text-body-size)] [&_h4]:[font-size:var(--tr-text-ui-size)] [&_h1]:font-semibold [&_h2]:font-semibold [&_h3]:font-semibold [&_h4]:font-semibold [&_h1]:text-[var(--text-primary)] [&_h2]:text-[var(--text-primary)] [&_h3]:text-[var(--text-primary)] [&_h4]:text-[var(--text-primary)] [&_h1]:mt-6 [&_h2]:mt-6 [&_h3]:mt-5 [&_h4]:mt-4 [&_h1]:mb-3 [&_h2]:mb-3 [&_h3]:mb-2 [&_h4]:mb-2 [&_h1:first-child]:mt-0 [&_h2:first-child]:mt-0 [&_h3:first-child]:mt-0 [&_h1]:border-b [&_h1]:border-[var(--border)] [&_h1]:pb-2 [&_p]:my-3 [&_ul]:my-3 [&_ol]:my-3 [&_ul]:pl-5 [&_ol]:pl-5 [&_ul]:list-disc [&_ol]:list-decimal [&_li]:my-1 [&_a]:text-[var(--accent)] [&_a]:underline [&_a]:underline-offset-2 [&_strong]:font-semibold [&_strong]:text-[var(--text-primary)] [&_em]:italic [&_code]:font-mono [&_code]:[font-size:var(--tr-text-small-size)] [&_code]:[font-weight:var(--tr-text-small-weight)] [&_code]:rounded-[var(--tr-radius-input)] [&_code]:px-1 [&_code]:py-px [&_code]:bg-[color-mix(in_srgb,var(--card-bg)_70%,transparent)] [&_code]:text-[var(--text-primary)] [&_pre]:my-3 [&_pre]:p-3 [&_pre]:rounded-[var(--tr-radius-md)] [&_pre]:overflow-x-auto [&_pre]:bg-[var(--card-bg)] [&_pre]:border [&_pre]:border-[var(--border)] [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_blockquote]:my-3 [&_blockquote]:pl-3 [&_blockquote]:border-l-2 [&_blockquote]:border-[var(--border)] [&_blockquote]:text-[var(--text-muted)] [&_hr]:my-5 [&_hr]:border-0 [&_hr]:border-t [&_hr]:border-[var(--border)] [&_table]:my-3 [&_table]:w-full [&_table]:border-collapse [&_table]:[font-size:var(--tr-text-small-size)] [&_table]:[font-weight:var(--tr-text-small-weight)] [&_th]:border [&_td]:border [&_th]:border-[var(--border)] [&_td]:border-[var(--border)] [&_th]:px-2 [&_td]:px-2 [&_th]:py-1 [&_td]:py-1 [&_th]:text-left [&_th]:font-semibold [&_th]:text-[var(--text-primary)] [&_th]:bg-[color-mix(in_srgb,var(--card-bg)_50%,transparent)] [&_img]:max-w-full [&_del]:line-through'
    : '[&_p]:my-0 [&_p]:mb-3 [&_p:last-child]:mb-0 [&_h2]:[font-size:var(--tr-text-subhead-size)] [&_h3]:[font-size:var(--tr-text-body-size)] [&_h4]:[font-size:var(--tr-text-ui-size)] [&_h2]:font-semibold [&_h3]:font-semibold [&_h4]:font-semibold [&_h2]:text-[var(--text-primary)] [&_h3]:text-[var(--text-primary)] [&_h4]:text-[var(--text-primary)] [&_h2]:mt-5 [&_h3]:mt-5 [&_h4]:mt-5 [&_h2]:mb-2 [&_h3]:mb-2 [&_h4]:mb-2 [&_h2]:leading-[1.3] [&_h3]:leading-[1.3] [&_h4]:leading-[1.3] [&_h2:first-child]:mt-0 [&_h3:first-child]:mt-0 [&_h4:first-child]:mt-0 [&_ul]:my-0 [&_ol]:my-0 [&_ul]:mb-3 [&_ol]:mb-3 [&_ul]:pl-[var(--space-chat-list-indent)] [&_ol]:pl-[var(--space-chat-list-indent)] [&_ul]:list-disc [&_ol]:list-decimal [&_li]:my-1 [&_a]:text-[var(--accent)] [&_a]:no-underline hover:[&_a]:underline [&_strong]:font-semibold [&_strong]:text-[var(--text-primary)] [&_em]:italic [&_code]:font-mono [&_code]:[font-size:var(--tr-text-body-size)] [&_code]:rounded-[var(--tr-radius-input)] [&_code]:px-1 [&_code]:py-px [&_code]:border [&_code]:border-[var(--border)] [&_code]:bg-[var(--card-hover)] [&_code]:text-[var(--text-primary)] [&_pre]:my-0 [&_pre]:mb-3 [&_pre]:p-[12px] [&_pre]:rounded-[var(--tr-radius-button)] [&_pre]:overflow-auto [&_pre]:bg-[var(--card-bg)] [&_pre]:border [&_pre]:border-[var(--border)] [&_pre_code]:bg-transparent [&_pre_code]:border-0 [&_pre_code]:p-0 [&_blockquote]:my-0 [&_blockquote]:mb-3 [&_blockquote]:pl-3 [&_blockquote]:border-l-2 [&_blockquote]:border-[var(--accent)] [&_blockquote]:text-[var(--text-secondary)] [&_hr]:my-5 [&_hr]:border-0 [&_hr]:border-t [&_hr]:border-[var(--divider)] [&_table]:mb-3 [&_table]:w-full [&_table]:border-collapse [&_table]:[font-size:var(--tr-text-small-size)] [&_table]:[font-weight:var(--tr-text-small-weight)] [&_th]:border [&_td]:border [&_th]:border-[var(--border)] [&_td]:border-[var(--border)] [&_th]:px-2 [&_td]:px-2 [&_th]:py-1 [&_td]:py-1 [&_th]:text-left [&_th]:font-semibold [&_del]:line-through'
  return <Text as="div" size={editor ? 'ui' : 'body'} weight={editor ? 'ui' : 'body'} tone={editor ? 'secondary' : 'primary'} leading={editor ? 'markdown' : 'chatMarkdown'} {...props} className={classes}>{children}</Text>
}
