import './prs.css'

const PRS_FOCUS_SHADOW = '0_0_0_3px_color-mix(in_srgb,var(--accent)_24%,transparent)'

export const PRS_CLASSES = {
  PRS_CLASS_1: 'text-[var(--ok)]',
  PRS_CLASS_2: 'h-3.5 w-3.5',
  PRS_CLASS_3: 'text-[var(--stop)]',
  PRS_CLASS_4: 'block h-3.5 w-3.5',
  PRS_CLASS_5: 'absolute -bottom-1 -right-1 text-[var(--warn)]',
  PRS_CLASS_6: 'flex min-w-0 flex-1 flex-col gap-1',
  PRS_CLASS_7: 'flex min-w-0 items-center gap-1.5',
  PRS_CLASS_8: 'shrink-0 font-mono text-[length:var(--tr-text-small-size)] text-[var(--text-muted)]',
  PRS_CLASS_9: 'min-w-0 truncate text-[length:var(--tr-text-ui-size)] text-[var(--text-primary)]',
  PRS_CLASS_10: 'prs-ml-1 flex shrink-0 items-center gap-1',
  PRS_CLASS_11: 'ml-auto flex shrink-0 gap-1.5 pl-2 font-mono text-[length:var(--tr-text-label-size)]',
  PRS_CLASS_12: 'flex min-w-0 items-center gap-1.5 text-[length:var(--tr-text-label-size)] text-[var(--text-muted)]',
  PRS_CLASS_13: 'max-w-28 truncate',
  PRS_CLASS_14: 'max-w-36 truncate',
  PRS_CLASS_15: 'inline-flex items-center gap-1 rounded-full border border-[color-mix(in_srgb,var(--border)_70%,transparent)] bg-[var(--hover-fill)] px-1.5 text-[length:var(--tr-text-label-size)] leading-[14px]',
  PRS_CLASS_16: 'h-[7px] w-[7px] rounded-full',
  PRS_CLASS_17: 'ml-auto shrink-0 tabular-nums',
  PRS_CLASS_18: 'flex flex-col gap-1',
  PRS_CLASS_19: 'flex items-center gap-2 px-3 pb-1 text-[length:var(--tr-text-small-size)] font-medium text-[color-mix(in_srgb,var(--text-muted)_85%,transparent)]',
  PRS_CLASS_20: 'tabular-nums opacity-60',
  PRS_CLASS_21: 'h-px min-w-2 flex-1 bg-[var(--divider)]',
  PRS_CLASS_22: 'flex flex-col gap-0.5',
  PRS_LIST_COLUMN: 'flex min-h-0 min-w-0 flex-1 flex-col',
  PRS_DETAIL_COLUMN: 'prs-detail-column pane-inspector',
  PRS_DETAIL_TABBAR: 'side-panel-header',
  PRS_DETAIL_ADD: 'prs-detail-add',
  PRS_DETAIL_MERGED: 'prs-detail-merged',
  PRS_DETAIL_CLOSED: 'prs-detail-closed',
  PRS_DETAIL_CONTENT: 'pane-inspector-content',
  PRS_STATE_MERGED_ICON: 'merged',
  PRS_STATE_CLOSED_ICON: 'closed',
  PRS_CLASS_24: 'flex h-11 shrink-0 items-center gap-3 px-5 text-[length:var(--tr-text-ui-size)]',
  PRS_CLASS_25: 'flex items-center gap-2.5 font-medium',
  PRS_CLASS_26: 'text-[var(--text-muted)]',
  PRS_CLASS_27: 'prs-compact-filter',
  PRS_CLASS_28: 'ml-auto flex gap-1',
  PRS_CLASS_29: 'inline-flex h-7 w-7 items-center justify-center rounded-[var(--tr-radius-sm)] text-[var(--text-muted)] hover:bg-[var(--hover-fill)] hover:text-[var(--text-primary)]',
  PRS_CLASS_30: 'fixed z-[var(--z-sticky)] min-w-52 rounded-[var(--tr-radius-md)] p-1 floating-glass floating-pop-in',
  PRS_CLASS_31: 'block w-full rounded px-2 py-1.5 text-left text-[length:var(--tr-text-small-size)] hover:bg-[var(--hover-fill)]',
  PRS_CLASS_32: 'min-h-0 flex-1 overflow-y-auto [mask-image:linear-gradient(to_bottom,transparent_0,#000_24px)]',
  PRS_CLASS_33: 'mx-auto flex w-full max-w-[1152px] flex-col gap-4 px-6 pb-12 pt-6',
  PRS_CLASS_34: 'flex flex-wrap items-center gap-2',
  PRS_CLASS_35: `flex h-8 min-w-[220px] flex-1 items-center gap-2 rounded-[var(--tr-radius-button)] border border-[var(--border)] bg-[color-mix(in_srgb,var(--text-primary)_2.5%,transparent)] px-[11px] text-[length:var(--tr-text-ui-size)] text-[var(--text-muted)] focus-within:border-[var(--accent)] focus-within:shadow-[${PRS_FOCUS_SHADOW}]`,
  PRS_CLASS_36: 'min-w-0 flex-1 border-0 bg-transparent text-[var(--text-primary)] outline-none focus-visible:shadow-[var(--focus-halo)] placeholder:text-[var(--text-muted)]',
  PRS_CLASS_37: 'relative',
  PRS_CLASS_38: 'inline-flex h-8 items-center gap-1.5 rounded-[var(--tr-radius-button)] border border-[var(--border)] bg-[color-mix(in_srgb,var(--text-primary)_3%,transparent)] px-[11px] text-[length:var(--tr-text-ui-size)] font-medium transition-colors duration-150 hover:bg-[color-mix(in_srgb,var(--text-primary)_6%,transparent)] active:scale-[.97]',
  PRS_CLASS_41: 'absolute left-0 top-full z-40 prs-mt-1 w-[200px] rounded-[var(--tr-radius-md)] p-1 floating-glass floating-pop-in [transform-origin:top_left]',
  PRS_CLASS_42: 'flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-[length:var(--tr-text-small-size)] hover:bg-[var(--hover-fill)]',
  PRS_CLASS_43: 'w-4',
  PRS_CLASS_44: 'rounded-full bg-[var(--hover-strong)] px-1.5 text-[length:var(--tr-text-label-size)]',
  PRS_CLASS_45: 'absolute right-0 top-full z-40 prs-mt-1 w-56 rounded-[var(--tr-radius-md)] p-1 floating-glass floating-pop-in [transform-origin:top_right]',
  PRS_CLASS_46: 'flex w-full items-center justify-between rounded px-2 py-1.5 text-left text-[length:var(--tr-text-small-size)] hover:bg-[var(--hover-fill)]',
  PRS_CLASS_47: 'flex items-center gap-2 text-[length:var(--tr-text-small-size)] text-[var(--text-muted)]',
  PRS_CLASS_48: 'flex h-8 w-8 items-center justify-center rounded-[var(--tr-radius-button)] border border-[var(--border)] bg-[color-mix(in_srgb,var(--text-primary)_3%,transparent)] transition-colors duration-150 hover:bg-[color-mix(in_srgb,var(--text-primary)_6%,transparent)] active:scale-[.97]',
  PRS_CLASS_49: 'h-px -mb-3',
  PRS_CLASS_50: 'flex flex-col gap-3',
  PRS_CLASS_51: 'flex flex-col gap-3 py-2',
  PRS_CLASS_52: 'h-12 animate-pulse rounded-[var(--tr-radius-button)] bg-[var(--hover-fill)]',
  PRS_CLASS_54: 'mx-2 max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-[var(--tr-radius-sm)] border border-[var(--divider)] bg-[color-mix(in_srgb,var(--text-primary)_5%,transparent)] px-2.5 py-2 font-mono text-[length:var(--tr-text-label-size)] leading-[1.6] text-[var(--text-secondary)]',
  PRS_CLASS_55: 'flex items-center gap-2 px-2 py-2',
  PRS_CLASS_56: 'text-[length:var(--tr-text-small-size)] text-[var(--text-muted)]',
  PRS_CLASS_57: 'flex-1',
  PRS_CLASS_58: 'text-[length:var(--tr-text-small-size)] text-[var(--ok)]',
  PRS_CLASS_59: 'underline',
  PRS_CLASS_60: 'inline-flex h-7 items-center gap-1 rounded border border-[var(--border)] px-2 text-[length:var(--tr-text-small-size)] hover:bg-[var(--hover-fill)]',
  PRS_CLASS_61: 'px-1 pb-1',
  PRS_CLASS_62: 'flex items-center px-2 pb-1 text-[length:var(--tr-text-small-size)] text-[var(--text-muted)]',
  PRS_CLASS_63: 'text-[length:var(--tr-text-label-size)] text-[var(--text-muted)]',
  PRS_CLASS_64: 'px-2 py-1.5 text-[length:var(--tr-text-small-size)] text-[var(--text-muted)]',
  PRS_CLASS_65: 'flex w-full items-center gap-2 rounded-[var(--tr-radius-sm)] px-2 py-1.5 text-left text-[length:var(--tr-text-small-size)] hover:bg-[var(--hover-fill)]',
  PRS_CLASS_66: 'min-w-0 flex-1 truncate',
  PRS_CLASS_67: 'shrink-0 text-[var(--text-muted)]',
  PRS_CLASS_68: 'grid transition-[grid-template-rows] duration-150 ease-out motion-reduce:transition-none',
  PRS_CLASS_69: 'min-h-0 overflow-hidden pb-1',
  PRS_CLASS_70: 'prs-mb-1 flex items-center justify-between text-[length:var(--tr-text-small-size)] text-[var(--text-muted)]',
  PRS_CLASS_71: 'inline-flex items-center gap-1',
  PRS_STATE_RUNNING: 'running',
  PRS_STATE_MERGED: 'merged',
  PRS_STATE_CLOSED: 'closed',
  PRS_AUTHOR_MAINTAINER: 'maintainer',
  PRS_CHECK_UNKNOWN: 'text-[var(--text-muted)]',
  PRS_CHECK_RUNNING: 'text-[var(--warn)]',
  PRS_CHECK_ROW: 'prs-mb-half rounded-[var(--tr-radius-sm)]',
  PRS_CHECK_ROW_EXPANDED: 'bg-[color-mix(in_srgb,var(--stop)_4%,transparent)]',
  PRS_CHECK_CHEVRON: 'text-[var(--text-muted)] transition-transform duration-150',
  PRS_ROTATE: 'transition-transform duration-150',
  PRS_ROTATE_CLOSED: '-rotate-90',
  PRS_PR_ROW: 'group flex w-full min-w-0 cursor-pointer items-center rounded-[var(--tr-radius-button)] px-3 py-[10px] text-left transition-colors duration-150 hover:bg-[var(--hover-fill)]',
  PRS_PR_ROW_SELECTED: 'prs-pr-row-selected',
  PRS_PR_STATE: 'relative prs-mr-2 prs-mt-nudge w-4 shrink-0',
  PRS_PR_STATE_MERGED: 'text-[color-mix(in_srgb,var(--accent)_60%,var(--stop))]',
  PRS_PR_STATE_CLOSED: 'text-[var(--text-muted)]',
  PRS_AUTHOR_AVATAR: 'flex h-3.5 w-3.5 shrink-0 items-center justify-center rounded-full text-[length:var(--tr-text-label-size)] text-white',
  PRS_AVATAR_MAINTAINER: 'bg-[#a77bff]',
  PRS_AVATAR_OTHER: 'bg-[#f26b73]',
  PRS_DRAFT_BADGE: 'shrink-0 rounded-[var(--tr-radius-sm)] border border-[var(--border)] px-1 text-[length:var(--tr-text-label-size)] text-[var(--text-muted)]',
  PRS_SORT_ICON: 'inline-flex w-4 items-center justify-center gap-0 text-[var(--text-muted)] [&>svg]:w-2',
} as const
