#!/usr/bin/env bash

BASELINE=(
  "ui/src/renderer/src/components/ConfirmModal.tsx 0"
  "ui/src/renderer/src/components/FirstRun.tsx 0"
  "ui/src/renderer/src/components/HostKeyModal.tsx 0"
  "ui/src/renderer/src/components/RenameTitle.tsx 0"
  "ui/src/renderer/src/components/SaveDiscardModal.tsx 0"
  "ui/src/renderer/src/components/SettingsView.tsx 0"
  "ui/src/renderer/src/components/ShortcutSheet.tsx 0"
  "ui/src/renderer/src/components/SshConnectModal.tsx 0"
  "ui/src/renderer/src/components/UpdateInstallModal.tsx 0"
  "ui/src/renderer/src/components/git/PrBrowse.tsx 0"
  "ui/src/renderer/src/components/git/PrPickers.tsx 0"
  "ui/src/renderer/src/components/git/PullRequestTab.tsx 0"
  "ui/src/renderer/src/components/git/WorktreeCleanupSection.tsx 30"
  "ui/src/renderer/src/components/git/WorktreesDialog.tsx 47"
  "ui/src/renderer/src/components/headBadge.ts 5"
  "ui/src/renderer/src/components/nav/McpSurface.tsx 0"
  "ui/src/renderer/src/components/nav/RoutinesSurface.tsx 0"
  "ui/src/renderer/src/components/tasks/RosterQueue.tsx 18"
  "ui/src/renderer/src/components/tasks/TaskChip.tsx 2"
  "ui/src/renderer/src/components/tasks/TaskComposer.tsx 20"
  "ui/src/renderer/src/components/tasks/TaskDetail.tsx 46"
  "ui/src/renderer/src/components/tasks/TaskExecution.tsx 21"
  "ui/src/renderer/src/components/tasks/TaskMenu.tsx 4"
  "ui/src/renderer/src/components/tasks/TaskNowCard.tsx 14"
  "ui/src/renderer/src/components/tasks/TaskRow.tsx 7"
  "ui/src/renderer/src/components/tasks/TasksList.tsx 13"
  "ui/src/renderer/src/components/tasks/TasksTab.tsx 5"
  "ui/src/renderer/src/components/tasks/glyphs.tsx 1"
  "ui/src/renderer/src/main.tsx 0"
  "ui/src/renderer/src/pane/TerminalPane.tsx 0"
  "ui/src/renderer/src/windowFocus.ts 0"
)
