#!/usr/bin/env bash
set -euo pipefail

# The version const and every shared numeric cap ride along (ts-rs exports only
# types): they are extracted from the Rust source so the UI cannot drift from
# the daemon -- a hand-mirrored copy once shipped a client one version behind.

cd "$(dirname "$0")/../core"
OUT="$(pwd)/../ui/src/renderer/src/houston/generated"
rm -rf "$OUT"
TS_RS_EXPORT_DIR="$OUT" cargo test -p houston-protocol --features ts-gen export_bindings --quiet

# ts-rs 10 ends a field's line with ", " whenever a doc comment follows it,
# leaving trailing whitespace in the emitted TS. Strip it so generated files
# stay clean under `git diff --check` and whitespace ratchets.
find "$OUT" -type f -name '*.ts' -exec sed -i 's/[[:space:]]*$//' {} +

VERSION="$(sed -nE 's/^pub const PROTOCOL_VERSION: u32 = ([0-9]+);$/\1/p' houston-protocol/src/lib.rs)"
[ -n "$VERSION" ] || { echo "could not extract PROTOCOL_VERSION from houston-protocol/src/lib.rs" >&2; exit 1; }
cat > "$OUT/PROTOCOL_VERSION.ts" <<EOF
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs), do not edit synchronized files
export const PROTOCOL_VERSION = $VERSION
EOF

RMS_FLOOR="$(sed -nE 's/^pub const DEFAULT_RMS_FLOOR: f32 = ([0-9.]+);$/\1/p' houston-protocol/src/lib.rs)"
[ -n "$RMS_FLOOR" ] || { echo "could not extract DEFAULT_RMS_FLOOR from houston-protocol/src/lib.rs" >&2; exit 1; }
extract_u32() {
  local v
  v="$(sed -nE "s/^pub const $1: (u32|u64|usize) = ([0-9_]+);\$/\2/p" houston-protocol/src/lib.rs | tr -d _)"
  [ -n "$v" ] || { echo "could not extract $1 from houston-protocol/src/lib.rs" >&2; exit 1; }
  echo "$v"
}
ROUTINES_TOTAL="$(extract_u32 ROUTINES_TOTAL)"
ROUTINE_NAME_MAX="$(extract_u32 ROUTINE_NAME_MAX)"
ROUTINE_PROMPT_MAX="$(extract_u32 ROUTINE_PROMPT_MAX)"
ROUTINE_MIN_INTERVAL_SECS="$(extract_u32 ROUTINE_MIN_INTERVAL_SECS)"
ROUTINE_TICK_MS="$(extract_u32 ROUTINE_TICK_MS)"
ROUTINE_RUNS_CONCURRENT="$(extract_u32 ROUTINE_RUNS_CONCURRENT)"
ROUTINE_RUN_MAX_MS="$(extract_u32 ROUTINE_RUN_MAX_MS)"
ROUTINE_RUNS_PAGE="$(extract_u32 ROUTINE_RUNS_PAGE)"
RESTORE_BUDGET_DEFAULT="$(extract_u32 RESTORE_BUDGET_DEFAULT)"
RESTORE_BUDGET_MAX="$(extract_u32 RESTORE_BUDGET_MAX)"
MAILBOX_RETENTION_HOURS_DEFAULT="$(extract_u32 MAILBOX_RETENTION_HOURS_DEFAULT)"
MAILBOX_RETENTION_HOURS_MAX="$(extract_u32 MAILBOX_RETENTION_HOURS_MAX)"
ORCHESTRATION_CAP_MAX="$(extract_u32 ORCHESTRATION_CAP_MAX)"
COMMAND_HISTORY_IGNORE_GLOBS_MAX="$(extract_u32 COMMAND_HISTORY_IGNORE_GLOBS_MAX)"
COMMAND_HISTORY_IGNORE_GLOB_LEN_MAX="$(extract_u32 COMMAND_HISTORY_IGNORE_GLOB_LEN_MAX)"
USAGE_MAX_WINDOW_DAYS="$(extract_u32 USAGE_MAX_WINDOW_DAYS)"
USAGE_WINDOW_REFUSED="$(sed -nE 's/^pub const USAGE_WINDOW_REFUSED: &str = "(.*)";$/\1/p' houston-protocol/src/lib.rs)"
[ -n "$USAGE_WINDOW_REFUSED" ] || { echo "could not extract USAGE_WINDOW_REFUSED from houston-protocol/src/lib.rs" >&2; exit 1; }
mapfile -t TAG_PALETTE_HEXES < <(sed -n '/^pub const TAG_PALETTE/,/^\];/p' houston-protocol/src/lib.rs | grep -oE '#[0-9a-fA-F]{6}')
[ "${#TAG_PALETTE_HEXES[@]}" -eq 11 ] || { echo "expected 11 TAG_PALETTE swatches, found ${#TAG_PALETTE_HEXES[@]}" >&2; exit 1; }
TAG_PALETTE_LIST="$(printf '"%s", ' "${TAG_PALETTE_HEXES[@]}")"
TAG_PALETTE_LIST="${TAG_PALETTE_LIST%, }"
MAX_TAG_NAME_LEN="$(extract_u32 MAX_TAG_NAME_LEN)"
MAX_TAGS_PER_SESSION="$(extract_u32 MAX_TAGS_PER_SESSION)"
cat > "$OUT/DEFAULTS.ts" <<EOF
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs), do not edit synchronized files
export const DEFAULT_RMS_FLOOR = $RMS_FLOOR
export const ROUTINES_TOTAL = $ROUTINES_TOTAL
export const ROUTINE_NAME_MAX = $ROUTINE_NAME_MAX
export const ROUTINE_PROMPT_MAX = $ROUTINE_PROMPT_MAX
export const ROUTINE_MIN_INTERVAL_SECS = $ROUTINE_MIN_INTERVAL_SECS
export const ROUTINE_TICK_MS = $ROUTINE_TICK_MS
export const ROUTINE_RUNS_CONCURRENT = $ROUTINE_RUNS_CONCURRENT
export const ROUTINE_RUN_MAX_MS = $ROUTINE_RUN_MAX_MS
export const ROUTINE_RUNS_PAGE = $ROUTINE_RUNS_PAGE
export const RESTORE_BUDGET_DEFAULT = $RESTORE_BUDGET_DEFAULT
export const RESTORE_BUDGET_MAX = $RESTORE_BUDGET_MAX
export const MAILBOX_RETENTION_HOURS_DEFAULT = $MAILBOX_RETENTION_HOURS_DEFAULT
export const MAILBOX_RETENTION_HOURS_MAX = $MAILBOX_RETENTION_HOURS_MAX
export const ORCHESTRATION_CAP_MAX = $ORCHESTRATION_CAP_MAX
export const COMMAND_HISTORY_IGNORE_GLOBS_MAX = $COMMAND_HISTORY_IGNORE_GLOBS_MAX
export const COMMAND_HISTORY_IGNORE_GLOB_LEN_MAX = $COMMAND_HISTORY_IGNORE_GLOB_LEN_MAX
export const USAGE_MAX_WINDOW_DAYS = $USAGE_MAX_WINDOW_DAYS
export const USAGE_WINDOW_REFUSED = '$USAGE_WINDOW_REFUSED'
export const TAG_PALETTE = [$TAG_PALETTE_LIST]
export const MAX_TAG_NAME_LEN = $MAX_TAG_NAME_LEN
export const MAX_TAGS_PER_SESSION = $MAX_TAGS_PER_SESSION
EOF
echo "generated $(ls "$OUT" | wc -l) file(s) in ui/src/renderer/src/houston/generated/ (protocol v$VERSION)"
