use houston_core::paths;
use tauri::Manager;

fn log_path_for(home: &std::path::Path, channel: Option<&str>) -> String {
    paths::log_dir_for(home, channel)
        .to_string_lossy()
        .into_owned()
}

#[tauri::command]
pub fn system_get_log_path() -> Result<String, String> {
    let home = dirs::home_dir()
        .ok_or_else(|| "system_get_log_path: cannot resolve home directory".to_string())?;
    let channel = paths::channel().map_err(|e| {
        format!("system_get_log_path: cannot resolve the channel's log directory: {e}")
    })?;
    Ok(log_path_for(&home, channel.as_deref()))
}

#[tauri::command]
pub fn system_get_home_dir() -> Result<String, String> {
    dirs::home_dir()
        .map(|p| p.to_string_lossy().into_owned())
        .ok_or_else(|| "system_get_home_dir: cannot resolve home directory".to_string())
}

fn read_licenses(path: &std::path::Path) -> Result<String, String> {
    std::fs::read_to_string(path).map_err(|e| {
        format!(
            "system_third_party_licenses: cannot read {}: {e}",
            path.display()
        )
    })
}

#[tauri::command]
pub fn system_third_party_licenses(app: tauri::AppHandle) -> Result<String, String> {
    let resource_path = app
        .path()
        .resolve(
            "resources/third-party-licenses.json",
            tauri::path::BaseDirectory::Resource,
        )
        .map_err(|e| {
            format!(
                "system_third_party_licenses: cannot resolve \
                 resources/third-party-licenses.json as a bundle resource: {e}"
            )
        })?;

    if resource_path.exists() {
        return read_licenses(&resource_path);
    }

    // Debug-only: `env!("CARGO_MANIFEST_DIR")` bakes this machine's absolute repository
    // path into the binary, and a shipped binary must never carry one. `dev.sh` runs the
    // debug binary straight out of target/debug, where no resource directory exists.
    #[cfg(debug_assertions)]
    {
        let dev_path = std::path::PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/resources/third-party-licenses.json"
        ));
        if dev_path.exists() {
            read_licenses(&dev_path)
        } else {
            Err(format!(
                "system_third_party_licenses: found neither {} nor {}; the file is generated by \
                 scripts/gen-third-party-licenses.mjs",
                resource_path.display(),
                dev_path.display()
            ))
        }
    }

    #[cfg(not(debug_assertions))]
    {
        Err(format!(
            "system_third_party_licenses: {} is missing; the file is generated by \
             scripts/gen-third-party-licenses.mjs",
            resource_path.display()
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn log_path_for_tracks_a_non_default_channel_without_mutating_process_env() {
        let home = dirs::home_dir().expect("test host must have a resolvable home dir");

        let release = log_path_for(&home, None);
        assert_eq!(release, paths::log_dir_for(&home, None).to_string_lossy());

        let dev = log_path_for(&home, Some("dev"));
        assert_eq!(
            dev,
            paths::log_dir_for(&home, Some("dev")).to_string_lossy()
        );

        assert_ne!(
            release, dev,
            "log_path_for must actually track the channel, not return a constant"
        );
    }

    #[test]
    fn system_get_log_path_agrees_with_paths_log_dir_in_this_process_env() {
        let expected = paths::log_dir().expect("log_dir() must resolve in a normal test env");
        let got =
            system_get_log_path().expect("system_get_log_path must succeed in a normal test env");
        assert_eq!(got, expected.to_string_lossy());
    }

    #[test]
    fn the_underlying_resolver_is_actually_channel_aware() {
        let home = dirs::home_dir().expect("test host must have a resolvable home dir");
        let release = paths::log_dir_for(&home, None);
        let dev = paths::log_dir_for(&home, Some("dev"));
        assert_ne!(
            release, dev,
            "release and dev channels must resolve to different log dirs"
        );
        assert!(release.ends_with("logs") && dev.ends_with("logs"));
    }

    #[test]
    fn system_get_home_dir_agrees_with_dirs_home_dir() {
        let expected = dirs::home_dir().expect("test host must have a resolvable home dir");
        let got =
            system_get_home_dir().expect("system_get_home_dir must succeed in a normal test env");
        assert_eq!(got, expected.to_string_lossy());
    }

    #[test]
    fn system_get_home_dir_agrees_with_the_home_env_var() {
        let Ok(home_env) = std::env::var("HOME") else {
            eprintln!("skipping: HOME env var is unset in this test environment");
            return;
        };
        let got =
            system_get_home_dir().expect("system_get_home_dir must succeed in a normal test env");
        assert_eq!(got, home_env);
    }

    fn generated_inventory() -> serde_json::Value {
        let raw = std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/resources/third-party-licenses.json"
        ))
        .expect(
            "the generated inventory must exist at src-tauri/resources/third-party-licenses.json",
        );
        serde_json::from_str(&raw).expect("the generated inventory must be valid JSON")
    }

    #[test]
    fn the_generated_inventory_is_valid_json_with_the_shape_the_renderer_expects() {
        let doc = generated_inventory();

        let obj = doc
            .as_object()
            .expect("the inventory's top level must be a JSON object");
        let mut keys: Vec<&str> = obj.keys().map(String::as_str).collect();
        keys.sort_unstable();
        assert_eq!(
            keys,
            vec!["packages", "texts"],
            "the inventory's top level must have exactly `texts` and `packages`, got {keys:?}"
        );

        let texts = obj["texts"]
            .as_object()
            .expect("`texts` must be a JSON object of id -> licence text");
        let packages = obj["packages"]
            .as_array()
            .expect("`packages` must be a JSON array");
        assert!(
            !packages.is_empty(),
            "`packages` must not be empty: the inventory names every shipped package"
        );

        for pkg in packages {
            let pkg_obj = pkg
                .as_object()
                .unwrap_or_else(|| panic!("every package must be a JSON object, got {pkg}"));
            let name = pkg_obj
                .get("name")
                .and_then(|v| v.as_str())
                .unwrap_or("<unnamed>");
            for field in [
                "origin",
                "name",
                "version",
                "license",
                "repository",
                "textIds",
            ] {
                assert!(
                    pkg_obj.contains_key(field),
                    "package {name:?} is missing the `{field}` field"
                );
            }
            let text_ids = pkg_obj["textIds"]
                .as_array()
                .unwrap_or_else(|| panic!("package {name:?}'s `textIds` must be an array"));
            for id in text_ids {
                let id = id
                    .as_str()
                    .unwrap_or_else(|| panic!("package {name:?} has a non-string text id {id}"));
                assert!(
                    texts.contains_key(id),
                    "package {name:?} references text id {id:?} which is not a key of `texts`"
                );
            }
        }
    }

    #[test]
    fn every_shipped_package_is_named_with_a_licence() {
        let doc = generated_inventory();

        let packages = doc["packages"]
            .as_array()
            .expect("`packages` must be a JSON array");

        let missing: Vec<String> = packages
            .iter()
            .filter(|pkg| {
                pkg.get("license")
                    .and_then(|v| v.as_str())
                    .is_none_or(str::is_empty)
            })
            .map(|pkg| {
                pkg.get("name")
                    .and_then(|v| v.as_str())
                    .unwrap_or("<unnamed package>")
                    .to_string()
            })
            .collect();

        assert!(
            missing.is_empty(),
            "every shipped package must name a non-empty licence; these do not: {missing:?}"
        );
    }
}
